title: "RandDouble Personal Blog"
author: Stefano Pilosio
email: stefano.pilosio@studenti.unimi.it
description: ""
baseurl: ""
url: "https://randdouble.github.io/"
github_username: RandDouble
# source: ./docs

remote_theme: pages-themes/minimal@v0.2.0
# theme: jekyll-theme-minima

lsi: false
safe: true
invremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: katex
  syntax_highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
